server:
  http_listen_port: 9080

positions:
  filename: /tmp/positions-core.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: open5gs-logs
    static_configs:
      - targets: [localhost]
        labels:
          job: open5gs
          domain: core
          __path__: /var/log/open5gs/*.log
  - job_name: docker-containers
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
    relabel_configs:
      - source_labels: [__meta_docker_container_name]
        target_label: container
